EPOCH: 100
ITERLENGTH: 250
VALIDATION_SPACE: 5
Checkpoint_Save_Space: 25
WARMUP: True
WARMUP_ITER: 5000
warm_up_val_space: 1000
Mix_Precision: True

Image_Dataset_Dir: 'clip_brain_mri/NPY_Dataset'
json_version: 'information'
have_modal: True
replace_norm: '头颅形态、大小未见异常。脑实质未见异常信号影，所见脑室形态及脑沟裂池未见异常扩张或变窄，中线结构未见移位。'
dataset_version: 2
return_word_vector: False
TextVector_Dataset_Dir: 'Text_Data'
ValidationNII_Dir: 'Validation'
Save_Dir: 'Models'
image_from_dir: 'None'
include_sample: 100
return_val: True
modal_embedding: True
modal_embedding_code: 'modal_embedding_code_5Modal'
modal_include:
  - ep2d_diff_3scan_trace_p2_TRACEW
  - ep2d_diff_3scan_trace_p2_ADC
  - t1_fl2d_tra
  - t2_tse_tra
  - FLAIR

batch_size: 64
image_lr: 0.0001
text_lr: 0.00005
load_bs: 7
MF_freq: 1
eps: 0.001

CLIP_frame: CLIP_Both_model
bert_attention_mask: True
return_logit: True
logit_sigmoid: False

loss_mode: 'align_TextSimNegKL'
loss_set:
  KL_mode: "batchmean"
  include_positive: True
  KL_way: 1
  sim_norm_mode: 'linear'
loss_alpha:
  NegKL: 1
  align: 1

image_encoder: 'ResNet'
image_model_depth: 50
image_encoder_params:
  n_input_channels: 1
  n_classes: 512

text_output_dim: 512

bert_weight_name: 'chinese-bert-wwm/ab0aa81da273504efc8540aa4d0bbaa3016a1bb5'
truncation: True
padding: 'max_length'
max_length: 256
return_tensors: 'pt'
bert_pooler_act: False

model_name: 'SeLIP'
gpu: '0'
device: 'cuda'
wait_count: 0
introduction: "SeLIP"