EPOCH: 50
ITERLENGTH: 50
VALIDATION_SPACE: 1
Checkpoint_Save_Space: 50
WARMUP: False
WARMUP_ITER: 250
Mix_Precision: False

Image_Dataset_size: 256
ValidationNII_Dir: 'Classfication'
Save_Dir: 'Transfer_Classfication'

sub_sample_num: None
batch_size: 6
image_lr: 0.0005
load_bs: 6

Seg_frame: Classify_Normal
model:
  initialize: True
  hidden_layer: None
  bottom_channel: 2048
  n_class: 2

Pretrain_path: 'Models/SeLIP/epoch_state_99.pth'

image_encoder: ResNet
image_model_depth: 50
image_encoder_params:
  n_input_channels: 1
  n_classes: 512
  return_stage: False

gpu: '0'
device: 'cuda'
wait_count: 0
introduction: "SeLIP"